### ISSUE TITLE
Not working with some .epub

### ISSUE THREAD

**Issue by PaolinoWhite** [dnkorpushov/ebookmeta#2] opened 2022-03-09 10:42 UTC
Hi,
why isn't working with some .epub files ?
Thank you

**Comment by single-fingal** [comment] 2022-04-05 18:46
Hi. Can you provide some more information on what behavior your seeing? In particular, Python exceptions/messages and stack traces would be helpful.

Two notes:
* I just made a pull request (#3) that resolves two issues that I was seeing, myself. The pull request is for single-fingal/ebookmeta@85e0e6c00c74b3ce8d10b85d63f46ae5dc1fbd0a. So you could take a look at my code to see if it resolves your issue(s).
* I also have a dev branch at single-fingal/ebookmeta which includes a few more minor updates right now. That might be worth exploring, too.

**Comment by RickVincent** [comment] 2022-06-12 05:00
@single-fingal,

This tool seem has issues on cover image part, especially on epub files with cover page id directed by another xhtml page.

BTW, thanks for your fixing. And saw you marked it as 0.11.5, but current ebookmeta version is 0.20.0. So is the fixing based on older version of ebookmeta?

**Comment by single-fingal** [comment] 2022-06-14 00:07
Hmm... For that, I'd have to see the error/stack trace that's reported by the program given your input. (Though, I'm no epub expert, myself, so I'd probably be limited only to making simple work-arounds for some problems.)

And you're right: my [dev branch](https://github.com/single-fingal/ebookmeta/tree/dev) was previously based on 0.11.5, but just a few minutes ago, I merged 0.20.0 into it, so it should have dnkorpushov's latest additions.

Sidenote: I haven't bothered to create a pull request for my dev branch because, at least for now, I'm not sure how useful my changes on that branch are (to the wider community). It helped me identify problematic epub files that I had, but the minor changes I made in that branch basically just fail (given certain conditions) in a "nicer way"; the changes so far mostly just have to do with reporting certain errors in a slightly more helpful way (at least, I thought so).

**Comment by dnkorpushov** [comment] 2022-06-15 16:02
@RickVincent  
In v1.0.0 the following algorithm is used to find the cover for epub in content.opf
Epub2:
1. Search `<meta name="cover" content=[cover_image_file_name]>`
2. If not found, get first item in manifest section. If item is xhtm, get first` <img src=[cover_image_file_name]>`

Epub3:
Only search item with properties="cover-image" in manifest section.

In version 1.0.0, the code was almost completely rewritten. Check for your bugs in this version.

P.S.
 
Sorry for my English :(

**Comment by RickVincent** [comment] 2022-06-17 17:03
@dnkorpushov 
Thanks for update with improvement! However, there are still some books with failing to get cover href. Attached some OPF files with issues by ebookmeta 1.0.3 for your reference.
[OPF.Samples.zip](https://github.com/dnkorpushov/ebookmeta/files/8929415/OPF.Samples.zip)

**Comment by RickVincent** [comment] 2022-06-19 07:11
@dnkorpushov

After studied some epub OPF files which the current ebookmeta (1.0.3) still hasn't processed,
Those OPFs have below structure:
1) No indicator in meta section. Just with item ID in manifest section. And its href is an xhtml page (2nd level)
2) There are couple types for cover image info in 2nd level xhtml page
in 2nd level page,
A. With "img" section, and href is in attribute "src"
B. With "image" section, and href is in attribute "xlink:href"

Attached my sample code based on your epub2.py code. (Key change is to call _get_cover_from_xhtml for 2nd level page parsing.)

Can you help to revise it and merge with you better Python programming skill? 💯  Thanks so much!

[epub2.Sample.py.txt](https://github.com/dnkorpushov/ebookmeta/files/8935809/epub2.Sample.py.txt)
[__init__.Sample.py.txt](https://github.com/dnkorpushov/ebookmeta/files/8935811/__init__.Sample.py.txt)
[metadata.Sample.py.txt](https://github.com/dnkorpushov/ebookmeta/files/8935812/metadata.Sample.py.txt)

**Comment by dnkorpushov** [comment] 2022-06-20 13:42
@RickVincent 
Can you send me sample opf and cover xhtml files for first and second cases from previous message?

**Comment by RickVincent** [comment] 2022-06-23 13:30
@dnkorpushov,

Attached are the sample opf and xhtml files for those cases, for your reference.
[The Civilization Origin.zip](https://github.com/dnkorpushov/ebookmeta/files/8967622/The.Civilization.Origin.zip)
[The Discreted World.zip](https://github.com/dnkorpushov/ebookmeta/files/8967625/The.Discreted.World.zip)

Other samples files are too to be uploaded here.

**Comment by RickVincent** [comment] 2022-06-23 14:33
@dnkorpushov,

BTW, can you help to see how to get ASIN# which is enclosed by _"<!-- BEGIN INFORMATION ONLY"_ such as below?
<!-- BEGIN INFORMATION ONLY 
<meta name="Cover ThumbNail Image" content="Images/thumb00262.jpeg" />
<meta name="Drm Ebookbase Book Id" content="0006018306102" />
<meta name="ASIN" content="B0B28KQ3NL" />

If the ASIN info is beyond _"<!-- BEGIN INFORMATION ONLY"_ section, I can fetch it correction by below method.
    def get_ASIN(self):
        node = self._get('opf:metadata/dc:identifier[@opf:scheme="ASIN"]')
        if node is not None:
            return xstr(node.text)
        node = self._get('opf:metadata/dc:identifier[@opf:scheme="MOBI-ASIN"]')
        if node is not None:
            return xstr(node.text)
        # If this is in <!-- BEGIN INFORMATION ONLY sectiob. Nothing to get. How to improve it?
        node = self._get('opf:metadata/opf:meta[@name="ASIN"]')
        print('Node Type is: ', type(node))
        if node is not None:
            return xstr(node.attrib['content'])

Attach such kind of opf for your reference. (Pls remove .txt extension due to github attachment constrain.)
[content.opf.txt](https://github.com/dnkorpushov/ebookmeta/files/8968214/content.opf.txt)

Any idea?

**Comment by dnkorpushov** [comment] 2022-06-24 11:51
@RickVincent,
Check version 1.1.2. Now covers get correct for your epub files.
>> can you help to see how to get ASIN# which is enclosed by "<!-- BEGIN INFORMATION ONLY" such as below?
It's impossible. The data is hidden by a comment. Such data is not visible to the parser that reads the metadata.

**Comment by dnkorpushov** [comment] 2022-06-24 11:52
I think, the problem is solved

**Closed as completed** 2022-06-24 11:51 UTC
